### ISSUE TITLE
If OTEL exporter is not available, server panics

### ISSUE THREAD

**Issue by miparnisari** [openfga/openfga#1216]
```
$ cat ~/.openfga/config.yaml

trace:
  enabled: true
  sampleRatio: 1
  otlpEndpoint: 0.0.0.0:4317%                   

                                      
[7/12/23 10:08:14] ~/GitHub/openfga $ make run
go build -o ./openfga ./cmd/openfga
./openfga run
2023-12-07T10:08:24.108-0800    INFO    🕵 tracing enabled: sampling ratio is 1 and se
nding traces to '0.0.0.0:4317', tls: false
panic: failed to establish a connection with the otlp exporter: context deadline excee
ded

goroutine 1 [running]:
github.com/openfga/openfga/pkg/telemetry.MustNewTracerProvider({0xc00054e150, 0x4, 0xc
0005cd700?})
        /Users/mparnisari/GitHub/openfga/pkg/telemetry/tracing.go:87 +0x739
github.com/openfga/openfga/cmd/run.(*ServerContext).Run(0xc00048f250, {0x20beec0, 0x2a
c44c0}, 0xc000042d80)
        /Users/mparnisari/GitHub/openfga/cmd/run/run.go:318 +0x54c
github.com/openfga/openfga/cmd/run.run(0xc000233f00?, {0x2ac44c0?, 0x4?, 0x1ede09f?})
        /Users/mparnisari/GitHub/openfga/cmd/run/run.go:276 +0xce
github.com/spf13/cobra.(*Command).execute(0xc0002c2600, {0x2ac44c0, 0x0, 0x0})
        /Users/mparnisari/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xa
a3
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002c2300)
        /Users/mparnisari/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x
3ff
github.com/spf13/cobra.(*Command).Execute(0xc0002c2300?)
        /Users/mparnisari/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x
13
main.main()
        /Users/mparnisari/GitHub/openfga/cmd/openfga/main.go:28 +0x12f
make: *** [run] Error 2
```

We should consider removing this line: https://github.com/openfga/openfga/blob/993c66ae5a81d66e51886e0d103c9cb1fc05d090/pkg/telemetry/tracing.go#L77

Also, slightly related: we should a test that ensures that if you try to start the server on X port but that port is already taken, you get an appropriate error message.

**Comment by jon-whit** [comment]
What's wrong with the server panic'ing in this case? That was intentional, not a bug. It's not an uncommon pattern to panic if server pre-requisite dependencies are not met.
